#-----------------------------------------------------------------------------
#
# Biocomfort Diagnostics GmbH & Co. KG
#            Copyright (c) 2008 - 2012. All Rights Reserved.
# Reproduction or modification is strictly prohibited without express
# written consent of Biocomfort Diagnostics GmbH & Co. KG.
#
#-----------------------------------------------------------------------------
#
# Contact: vollmer@biocomfort.de
#
#-----------------------------------------------------------------------------
#
# Filename: settings.yml
#
#-----------------------------------------------------------------------------

development: &non_production_settings
  host: localhost:3000
  site_url: http://localhost:3000
  site_name: Biocomfort Remote Management Platform
  admin_email: admin@test.me

test:
  <<: *non_production_settings

cucumber:
  <<: *non_production_settings

staging:
  host: brmp.aentos.net
  site_url: https://brmp.aentos.net
  site_name: Biocomfort Remote Management Platform
  admin_email: info@aentos.es

production:
  host: rmp.biocomfort.de
  site_url: https://rmp.biocomfort.de
  site_name: Biocomfort Remote Management Platform
  admin_email: rmp@aentos.es
